// بيانات دفعة استيراد 28 قفل باب مكينة الصابون الأوتوماتيكية — مُستخرجة آلياً
// ومُتحقَّق منها حرفياً (صفر اختلاف) مقابل نفس البيانات الحقيقية الموجودة أصلاً
// فـ supabase/migrations/20260813000000_import_door_lock_products.sql (commit 8f66fd6).
// لا تُعدَّل يدوياً — أي تغيير هنا يفصلها عن الملف الأصلي الذي بقي المصدر الرسمي.
export type DoorLockImportImage = {
  path: string;
  alt: string;
  sortOrder: number;
  isPrimary: boolean;
};

export type DoorLockImportProduct = {
  sku: string;
  slug: string;
  categoryId: number;
  nameAr: string;
  descriptionAr: string;
  unitLabel: string;
  minOrderQty: number;
  qtyIncrement: number;
  purchasePrice: number;
  salePrice: number;
  stockQuantity: number;
  status: "draft" | "published" | "out_of_stock";
  sortOrder: number;
  images: DoorLockImportImage[];
};

export const DOOR_LOCK_IMPORT_PRODUCTS: DoorLockImportProduct[] = [
  {
    sku: "TF-AWM-001",
    slug: "automatic-washer-door-lock-model-01",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 1",
    descriptionAr: "قفل باب كامل بهيكل بلاستيكي أبيض، مدخل مستطيل للسان الباب، تثبيت بفتحتين، وفيشتان منفصلتان للتوصيل كما هو موضح في الصور. يُرجى قبل الطلب مقارنة شكل القفل والفيش وأطراف التوصيل ومواضع التثبيت مع القطعة الأصلية لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 100.0,
    salePrice: 150.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 1,
    images: [
      { path: "product-images/TF-AWM-001/TF-AWM-001-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 1 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-001/TF-AWM-001-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 1 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-001/TF-AWM-001-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 1 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-002",
    slug: "automatic-washer-door-lock-model-02",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 2",
    descriptionAr: "قفل باب طويل بهيكل أبيض وأسود، مدخل مستطيل للسان الباب، فيشة سوداء واحدة تحتوي على 3 أطراف توصيل، وواجهة تثبيت بها 4 فتحات. يُرجى قبل الطلب مقارنة شكل القفل والفيشة وأطراف التوصيل ومواضع التثبيت مع القطعة الأصلية لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 100.0,
    salePrice: 150.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 2,
    images: [
      { path: "product-images/TF-AWM-002/TF-AWM-002-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 2 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-002/TF-AWM-002-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 2 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-002/TF-AWM-002-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 2 - صورة 3", sortOrder: 3, isPrimary: false },
      { path: "product-images/TF-AWM-002/TF-AWM-002-4.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 2 - صورة 4", sortOrder: 4, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-003",
    slug: "automatic-washer-door-lock-model-03",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 3",
    descriptionAr: "قفل باب طويل بهيكل رمادي وواجهة علوية سوداء، مدخل مستطيل للسان الباب، فتحتان للتثبيت، وفيشة جانبية مدمجة بثلاثة أطراف توصيل. يُرجى قبل الطلب مقارنة شكل القفل والفيشة وأطرافها ومواضع التثبيت مع القطعة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 80.0,
    salePrice: 120.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 3,
    images: [
      { path: "product-images/TF-AWM-003/TF-AWM-003-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 3 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-003/TF-AWM-003-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 3 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-003/TF-AWM-003-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 3 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-004",
    slug: "automatic-washer-door-lock-model-04",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 4",
    descriptionAr: "قفل باب بهيكل بلاستيكي أسود، مدخل مستطيل للسان الباب، فتحتان دائريتان للتثبيت، وفيشة جانبية بثلاثة أطراف توصيل. يُرجى قبل الطلب مقارنة شكل القفل والفيشة وعدد أطرافها واتجاه مدخل اللسان ومواضع التثبيت مع القطعة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 140.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 4,
    images: [
      { path: "product-images/TF-AWM-004/TF-AWM-004-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 4 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-004/TF-AWM-004-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 4 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-004/TF-AWM-004-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 4 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-005",
    slug: "automatic-washer-door-lock-model-05",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 5",
    descriptionAr: "قفل باب بتصميم طويل ورفيع وهيكل بلاستيكي بلون بني داكن، مع مدخل مستطيل للسان الباب في الجهة العلوية وفتحات دائرية مخصصة للتركيب. يُرجى قبل الطلب مقارنة الشكل العام، أبعاد القفل، اتجاه مدخل اللسان، فتحات التثبيت ونقاط التوصيل مع القطعة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 70.0,
    salePrice: 100.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 5,
    images: [
      { path: "product-images/TF-AWM-005/TF-AWM-005-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 5 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-005/TF-AWM-005-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 5 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-005/TF-AWM-005-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 5 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-006",
    slug: "automatic-washer-door-lock-model-06",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 6",
    descriptionAr: "قفل باب بتصميم طويل ومستطيل وهيكل بلاستيكي بلون بني داكن وأسود، مع جهة توصيل مدمجة تضم 4 أطراف معدنية ظاهرة. يُرجى قبل الطلب مقارنة الشكل والأبعاد، اتجاه التركيب، عدد أطراف التوصيل وترتيبها مع القفل والفيشة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 70.0,
    salePrice: 100.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 6,
    images: [
      { path: "product-images/TF-AWM-006/TF-AWM-006-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 6 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-006/TF-AWM-006-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 6 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-006/TF-AWM-006-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 6 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-007",
    slug: "automatic-washer-door-lock-model-07",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 7",
    descriptionAr: "قفل باب بتصميم طويل وهيكل بلاستيكي بني، مزود بدعامة معدنية داخلية ومدخل مستطيل للسان الباب في الأعلى، مع 3 أطراف توصيل مسطحة جانبية ظاهرة ومواصفة 220V مكتوبة على القطعة. يُرجى قبل الطلب مقارنة الشكل والأبعاد، مدخل اللسان، فتحات التثبيت، عدد أطراف التوصيل وترتيبها مع القفل والفيشة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 60.0,
    salePrice: 80.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 7,
    images: [
      { path: "product-images/TF-AWM-007/TF-AWM-007-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 7 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-007/TF-AWM-007-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 7 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-007/TF-AWM-007-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 7 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-008",
    slug: "automatic-washer-door-lock-model-08",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 8",
    descriptionAr: "قفل باب بهيكل بلاستيكي أسود، مدخل مستطيل عريض للسان الباب، وفيشة بيضاء جانبية مدمجة تضم 3 أطراف توصيل معدنية. تظهر على القطعة مواصفة 16(6)A 250V~. يُرجى قبل الطلب مقارنة الشكل العام، اتجاه مدخل اللسان، شكل الفيشة، عدد أطرافها وترتيبها ومواضع التثبيت مع القفل والفيشة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 140.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 8,
    images: [
      { path: "product-images/TF-AWM-008/TF-AWM-008-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 8 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-008/TF-AWM-008-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 8 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-008/TF-AWM-008-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 8 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-009",
    slug: "automatic-washer-door-lock-model-09",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 9",
    descriptionAr: "قفل باب بهيكل بلاستيكي أسود وأبيض، مدخل مستطيل عريض للسان الباب في الأعلى، فتحتان جانبيتان للتثبيت، وفيشة مدمجة تضم 4 أطراف توصيل معدنية ظاهرة. تظهر على القطعة مواصفة 16(6)A 250V~. يُرجى قبل الطلب مقارنة الشكل العام، اتجاه مدخل اللسان، شكل الفيشة، عدد أطرافها وترتيبها ومواضع التثبيت مع القفل والفيشة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 150.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 9,
    images: [
      { path: "product-images/TF-AWM-009/TF-AWM-009-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 9 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-009/TF-AWM-009-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 9 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-009/TF-AWM-009-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 9 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-010",
    slug: "automatic-washer-door-lock-model-10",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 10",
    descriptionAr: "قفل باب بهيكل بلاستيكي أسود وأبيض وتصميم غير متماثل، مع مدخل مستطيل للسان الباب في الأسفل وذراع ميكانيكي جانبي، وفيشة بيضاء مدمجة تضم 3 أطراف توصيل معدنية ظاهرة. يُرجى قبل الطلب مقارنة الشكل العام، اتجاه مدخل اللسان والذراع الجانبي، شكل الفيشة، عدد أطرافها وترتيبها ومواضع التثبيت مع القفل والفيشة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 140.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 10,
    images: [
      { path: "product-images/TF-AWM-010/TF-AWM-010-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 10 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-010/TF-AWM-010-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 10 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-010/TF-AWM-010-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 10 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-011",
    slug: "automatic-washer-door-lock-model-11",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 11",
    descriptionAr: "قفل باب بهيكل بلاستيكي أسود وأبيض، مدخل مستطيل عريض للسان الباب، ذراع ميكانيكي جانبي طويل، وفيشة بيضاء مدمجة تضم 3 أطراف توصيل معدنية ظاهرة. تظهر على القطعة مواصفة 4-5 16(6)A 250V~ والمرجع DKS08. يُرجى قبل الطلب مقارنة الشكل العام، اتجاه مدخل اللسان والذراع الجانبي، شكل الفيشة، عدد أطرافها وترتيبها ومواضع التثبيت مع القفل والفيشة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 140.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 11,
    images: [
      { path: "product-images/TF-AWM-011/TF-AWM-011-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 11 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-011/TF-AWM-011-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 11 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-011/TF-AWM-011-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 11 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-012",
    slug: "automatic-washer-door-lock-model-12",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 12",
    descriptionAr: "قفل باب بتصميم طويل وهيكل بلاستيكي أسود وأبيض، قاعدة تثبيت مثلثة بفتحتين ملولبتين، ومدخل مستطيل عريض للسان الباب في الأسفل. مزود بفيشة بيضاء جانبية تضم 3 أطراف توصيل معدنية، وتظهر على القطعة عبارة DM SERIES. يُرجى قبل الطلب مقارنة الشكل والأبعاد، اتجاه مدخل اللسان، المسافة بين فتحتي التثبيت، شكل الفيشة وعدد أطرافها وترتيبها مع القفل والفيشة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 140.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 12,
    images: [
      { path: "product-images/TF-AWM-012/TF-AWM-012-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 12 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-012/TF-AWM-012-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 12 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-012/TF-AWM-012-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 12 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-013",
    slug: "automatic-washer-door-lock-model-13",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 13",
    descriptionAr: "قفل باب بهيكل بلاستيكي أبيض وأسود، مدخل مستطيل عريض للسان الباب، ذراع ميكانيكي جانبي، وفيشة بيضاء مدمجة تضم 3 أطراف توصيل معدنية ظاهرة. تظهر على القطعة مواصفة 1-2 16(6)A 250V~ والمرجع DKS67A. يُرجى قبل الطلب مقارنة الشكل العام، اتجاه مدخل اللسان والذراع الجانبي، شكل الفيشة، عدد أطرافها وترتيبها ومواضع التثبيت مع القفل والفيشة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 140.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 13,
    images: [
      { path: "product-images/TF-AWM-013/TF-AWM-013-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 13 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-013/TF-AWM-013-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 13 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-013/TF-AWM-013-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 13 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-014",
    slug: "automatic-washer-door-lock-model-14",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 14",
    descriptionAr: "قفل باب كبير بهيكل بلاستيكي أبيض وتصميم مسطح، مدخل مستطيل عميق للسان الباب في الواجهة، وذراع ميكانيكي علوي. مزود بفيشة مدمجة تضم 3 أطراف توصيل معدنية ظاهرة. يُرجى قبل الطلب مقارنة الشكل والأبعاد، اتجاه مدخل اللسان والذراع، شكل الفيشة، عدد أطرافها وترتيبها ونقاط التثبيت مع القفل والفيشة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 150.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 14,
    images: [
      { path: "product-images/TF-AWM-014/TF-AWM-014-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 14 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-014/TF-AWM-014-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 14 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-014/TF-AWM-014-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 14 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-015",
    slug: "automatic-washer-door-lock-model-15",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 15",
    descriptionAr: "قفل باب كبير بهيكل بلاستيكي أبيض وأسود، مدخل مستطيل عميق للسان الباب في الواجهة، وذراع ميكانيكي علوي. مزود بفيشة بيضاء مدمجة تضم 3 أطراف توصيل معدنية ظاهرة. تظهر على القطعة مواصفة 1-2 16(6)A 250V~ والمرجع DKS67A. يُرجى قبل الطلب مقارنة الشكل والأبعاد، اتجاه مدخل اللسان والذراع، شكل الفيشة، عدد أطرافها وترتيبها ونقاط التثبيت مع القفل والفيشة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 140.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 15,
    images: [
      { path: "product-images/TF-AWM-015/TF-AWM-015-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 15 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-015/TF-AWM-015-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 15 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-015/TF-AWM-015-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 15 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-016",
    slug: "automatic-washer-door-lock-model-16",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 16",
    descriptionAr: "قفل باب بتصميم طويل وهيكل بلاستيكي أبيض مع جزء داخلي بني، مدخل مستطيل للسان الباب في الأعلى، وقاعدة تثبيت علوية بفتحتين دائريتين. مزود بفيشة مدمجة تضم 3 أطراف توصيل معدنية ظاهرة. يُرجى قبل الطلب مقارنة الشكل والأبعاد، اتجاه مدخل اللسان، المسافة بين فتحتي التثبيت، شكل الفيشة، عدد أطرافها وترتيبها مع القفل والفيشة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 50.0,
    salePrice: 80.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 16,
    images: [
      { path: "product-images/TF-AWM-016/TF-AWM-016-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 16 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-016/TF-AWM-016-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 16 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-016/TF-AWM-016-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 16 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-017",
    slug: "automatic-washer-door-lock-model-17",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 17",
    descriptionAr: "قفل باب بهيكل بلاستيكي أسود مدمج، مدخل مستطيل للسان الباب في الأسفل، فتحتان دائريتان للتثبيت، وذراع ميكانيكي علوي جانبي. مزود بفيشة بيضاء مدمجة تضم 3 أطراف توصيل معدنية ظاهرة. تظهر على القطعة مواصفة T85 و16(6)A 250V~. يُرجى قبل الطلب مقارنة الشكل والأبعاد، اتجاه مدخل اللسان والذراع، المسافة بين فتحتي التثبيت، شكل الفيشة، عدد أطرافها وترتيبها مع القفل والفيشة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 150.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 17,
    images: [
      { path: "product-images/TF-AWM-017/TF-AWM-017-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 17 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-017/TF-AWM-017-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 17 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-017/TF-AWM-017-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 17 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-018",
    slug: "automatic-washer-door-lock-model-18",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 18",
    descriptionAr: "قفل باب بهيكل بلاستيكي أسود وأبيض، مدخل مستطيل عريض للسان الباب في الأعلى، وفتحتان دائريتان جانبيتان للتثبيت. مزود بفيشة بيضاء مدمجة تضم 4 أطراف توصيل معدنية ظاهرة. يُرجى قبل الطلب مقارنة الشكل والأبعاد، اتجاه مدخل اللسان، المسافة بين فتحتي التثبيت، شكل الفيشة، عدد أطرافها وترتيبها مع القفل والفيشة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 150.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 18,
    images: [
      { path: "product-images/TF-AWM-018/TF-AWM-018-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 18 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-018/TF-AWM-018-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 18 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-018/TF-AWM-018-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 18 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-019",
    slug: "automatic-washer-door-lock-model-19",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 19",
    descriptionAr: "قفل باب بتصميم طويل وهيكل بلاستيكي أبيض وأحمر، مدخل مستطيل للسان الباب في الأعلى، وقاعدة علوية تضم أربع فتحات دائرية. مزود بفيشة جانبية حمراء تضم 3 أطراف توصيل معدنية ظاهرة، وتظهر على القطعة مواصفة 220V و16(6)A. يُرجى قبل الطلب مقارنة الشكل والأبعاد، اتجاه مدخل اللسان، فتحات التثبيت، شكل الفيشة، عدد أطرافها وترتيبها مع القفل والفيشة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 45.0,
    salePrice: 70.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 19,
    images: [
      { path: "product-images/TF-AWM-019/TF-AWM-019-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 19 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-019/TF-AWM-019-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 19 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-019/TF-AWM-019-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 19 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-020",
    slug: "automatic-washer-door-lock-model-20",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 20",
    descriptionAr: "قفل باب بتصميم طويل وهيكل بلاستيكي رمادي فاتح، مدخل مستطيل عريض للسان الباب في الأعلى، وقاعدة تثبيت طويلة بفتحتين دائريتين مع آلية جانبية. مزود بفيشة مدمجة تضم 3 أطراف توصيل معدنية ظاهرة. يُرجى قبل الطلب مقارنة الشكل والأبعاد، اتجاه مدخل اللسان، المسافة بين فتحتي التثبيت، شكل الفيشة، عدد أطرافها وترتيبها مع القفل والفيشة الأصلية والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 150.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 20,
    images: [
      { path: "product-images/TF-AWM-020/TF-AWM-020-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 20 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-020/TF-AWM-020-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 20 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-020/TF-AWM-020-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 20 - صورة 3", sortOrder: 3, isPrimary: false },
      { path: "product-images/TF-AWM-020/TF-AWM-020-4.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 20 - صورة 4", sortOrder: 4, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-021",
    slug: "automatic-washer-door-lock-model-21",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 21",
    descriptionAr: "قفل أمان باب بتصميم طويل وهيكل بلاستيكي أبيض، مدخل مستطيل عريض للسان الباب في الأعلى، وفتحتان دائريتان علويتان للتثبيت. يتضمن صفيحة معدنية داخلية مع نوابض ظاهرة، وفيشة جانبية مدمجة تضم 4 أطراف توصيل مرقمة من 2 إلى 5. يُرجى قبل الطلب مقارنة شكل القطعة وأبعادها، اتجاه مدخل اللسان، المسافة بين فتحتي التثبيت، شكل الفيشة وعدد أطرافها وترتيبها مع القفل والفيشة الأصليين والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 150.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 21,
    images: [
      { path: "product-images/TF-AWM-021/TF-AWM-021-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 21 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-021/TF-AWM-021-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 21 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-021/TF-AWM-021-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 21 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-022",
    slug: "automatic-washer-door-lock-model-22",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 22",
    descriptionAr: "قفل أمان باب بهيكل بلاستيكي أسود عريض، مدخل جانبي مستطيل للسان الباب، وفتحتان دائريتان للتثبيت موزعتان بشكل مائل. يتضمن صفيحة معدنية داخلية وآلية بنابض، وموصلاً كهربائياً مدمجاً داخل غطاء مستطيل عريض بثلاث خانات ظاهرة. يظهر على الهيكل المرجع 126060704. يُرجى قبل الطلب مقارنة شكل القطعة وأبعادها، اتجاه مدخل اللسان، مواضع فتحتي التثبيت، شكل الفيشة وخاناتها مع القفل والفيشة الأصليين والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 60.0,
    salePrice: 100.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 22,
    images: [
      { path: "product-images/TF-AWM-022/TF-AWM-022-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 22 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-022/TF-AWM-022-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 22 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-022/TF-AWM-022-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 22 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-023",
    slug: "automatic-washer-door-lock-model-23",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 23",
    descriptionAr: "قفل أمان باب بتصميم طويل وهيكل بلاستيكي أبيض مع جزء علوي أسود، مدخل مستطيل للسان الباب في الأعلى، وقاعدة علوية تضم أربع فتحات دائرية لاختيار موضع التثبيت. مزود بفيشة جانبية مدمجة تضم 3 أطراف توصيل معدنية ظاهرة، ويظهر على القطعة المرجع 320033136. يُرجى قبل الطلب مقارنة شكل القطعة وأبعادها، اتجاه مدخل اللسان، فتحات التثبيت، شكل الفيشة وعدد أطرافها وترتيبها مع القفل والفيشة الأصليين والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 45.0,
    salePrice: 70.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 23,
    images: [
      { path: "product-images/TF-AWM-023/TF-AWM-023-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 23 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-023/TF-AWM-023-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 23 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-023/TF-AWM-023-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 23 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-024",
    slug: "automatic-washer-door-lock-model-24",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 24",
    descriptionAr: "قفل أمان باب بهيكل بلاستيكي رمادي وأسود، مدخل مستطيل عميق للسان الباب في الجزء العلوي، وآلية تثبيت جانبية مع ذراع ميكانيكي. مزود بفيشة بيضاء مدمجة تضم 3 أطراف توصيل معدنية ظاهرة. تظهر على القطعة المواصفة T85 IE4 و1-2 16(6)A 250V~ والمرجع DK042. يُرجى قبل الطلب مقارنة شكل القطعة وأبعادها، اتجاه مدخل اللسان والذراع، نقاط التثبيت، شكل الفيشة وعدد أطرافها وترتيبها مع القفل والفيشة الأصليين والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 140.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 24,
    images: [
      { path: "product-images/TF-AWM-024/TF-AWM-024-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 24 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-024/TF-AWM-024-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 24 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-024/TF-AWM-024-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 24 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-025",
    slug: "automatic-washer-door-lock-model-25",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 25",
    descriptionAr: "قفل أمان باب بتصميم طويل وهيكل بلاستيكي أسود وأبيض مع جزء داخلي بني، مدخل مستطيل للسان الباب في الأعلى، وقاعدة علوية تضم أربع فتحات دائرية لاختيار موضع التثبيت. مزود بفيشة جانبية بنية تضم 3 أطراف توصيل معدنية مرقمة 1 و3 و2. تظهر على القطعة المواصفات ZV-446 و250V~ T110 و16(6)A CLOSING و10(4)A OPENING، والمرجع 72805310400. يُرجى قبل الطلب مقارنة شكل القطعة وأبعادها، اتجاه مدخل اللسان، فتحات التثبيت، شكل الفيشة وعدد أطرافها وترتيبها مع القفل والفيشة الأصليين والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 50.0,
    salePrice: 80.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 25,
    images: [
      { path: "product-images/TF-AWM-025/TF-AWM-025-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 25 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-025/TF-AWM-025-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 25 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-025/TF-AWM-025-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 25 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-026",
    slug: "automatic-washer-door-lock-model-26",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 26",
    descriptionAr: "قفل أمان باب بتصميم طويل وهيكل بلاستيكي أبيض مع آلية علوية سوداء، مدخل مستطيل للسان الباب في الأعلى، ودليل تثبيت جانبي بارز. مزود بفيشة جانبية بيضاء تضم 3 أطراف توصيل معدنية مرقمة 1 و2 و3. تظهر على القطعة مواصفات T85 IE4 و16(6)A 250V~ CLOSING و10(2)A 250V~ OPENING. يُرجى قبل الطلب مقارنة شكل القطعة وأبعادها، اتجاه مدخل اللسان والدليل الجانبي، نقاط التثبيت، شكل الفيشة وعدد أطرافها وترتيبها مع القفل والفيشة الأصليين والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 150.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 26,
    images: [
      { path: "product-images/TF-AWM-026/TF-AWM-026-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 26 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-026/TF-AWM-026-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 26 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-026/TF-AWM-026-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 26 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-027",
    slug: "automatic-washer-door-lock-model-27",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 27",
    descriptionAr: "قفل أمان باب بهيكل بلاستيكي أسود عريض، مدخل جانبي مستطيل للسان الباب، وآلية ميكانيكية جانبية مع ذراع بارز وعدة نقاط للتثبيت. مزود بوحدة كهربائية بيضاء وفيشة مدمجة تضم 3 أطراف توصيل معدنية مرقمة 3 و2 و1. تظهر على القطعة العلامة Metalflex والطراز ZV-447، والمرجعان V13305 و0024000128D، إضافة إلى المواصفة T85 IE4 و1-2 16(6)A 250VAC. يُرجى قبل الطلب مقارنة شكل القطعة وأبعادها، اتجاه مدخل اللسان والذراع، نقاط التثبيت، شكل الفيشة وعدد أطرافها وترتيبها والمراجع المكتوبة مع القفل والفيشة الأصليين والصور لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 90.0,
    salePrice: 140.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 27,
    images: [
      { path: "product-images/TF-AWM-027/TF-AWM-027-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 27 - صورة 1", sortOrder: 1, isPrimary: true },
      { path: "product-images/TF-AWM-027/TF-AWM-027-2.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 27 - صورة 2", sortOrder: 2, isPrimary: false },
      { path: "product-images/TF-AWM-027/TF-AWM-027-3.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 27 - صورة 3", sortOrder: 3, isPrimary: false },
    ],
  },
  {
    sku: "TF-AWM-028",
    slug: "automatic-washer-door-lock-model-28",
    categoryId: 16,
    nameAr: "قفل أمان باب مكينة الصابون الأوتوماتيكية – موديل 28",
    descriptionAr: "قفل أمان باب بهيكل مركب من وحدة كهربائية بلاستيكية رمادية وآلية قفل سوداء، مع مدخل مستطيل جانبي للسان الباب وقاعدة سوداء تضم نقطتي تثبيت دائريتين. مزود بفيشة مدمجة تظهر عليها أرقام أطراف التوصيل 2 و3 و5. تظهر على القطعة العلامة ROLD وعبارة DF SERIES، إضافة إلى المواصفات 4-5 16(6)A 250V~ وIE4 وT85. يُرجى قبل الطلب مقارنة شكل القطعة وأبعادها، اتجاه مدخل اللسان، مواضع التثبيت، شكل الفيشة وأرقام وترتيب أطرافها والمواصفات المكتوبة مع القفل والفيشة الأصليين والصورة لضمان التوافق.\n\nلضمان التوافق، قارن القطعة الأصلية مع جميع الصور، خصوصاً شكل الهيكل، والفيشة، وعدد وترتيب أطراف التوصيل، ولسان القفل، ومواضع التثبيت. الاعتماد على شكل الماكينة وحده غير كافٍ.",
    unitLabel: "قطعة",
    minOrderQty: 1,
    qtyIncrement: 1,
    purchasePrice: 70.0,
    salePrice: 150.0,
    stockQuantity: 500,
    status: "published" as const,
    sortOrder: 28,
    images: [
      { path: "product-images/TF-AWM-028/TF-AWM-028-1.jpg", alt: "قفل باب مكينة الصابون الأوتوماتيكية موديل 28 - صورة 1", sortOrder: 1, isPrimary: true },
    ],
  },
];
